### ISSUE TITLE
Could not resolve ***/vite.content.config.ts

### ISSUE THREAD

**Issue by hbalxzdl** [Wyatex/vue3-crx-starter#1]
Could not resolve "/vite.content.config.ts"

Could not resolve entry module "index.html".
 ELIFECYCLE  Command failed with exit code 1.
error during build:
RollupError: Could not resolve entry module "index.html".

**Comment by Wyatex** [comment]
之前改过的源代码可能忘记提交了，而且找不到了，我刚刚补了一下应该可以了。
改了一点点东西，可以看下readme
